// src/constants/config/brew/pourover/pouroverConfig.js
import { BREW_BASE } from '../_base';

export const POUROVER_STATIC_OPTIONS = {
  dripper: [
    { label: 'Origami', value: 'origami' },
    { label: 'V60', value: 'v60' },
  ],
  cup: [
    { label: 'Ceramic', value: 'ceramic' },
    { label: 'Glass', value: 'glass' },
    { label: 'Origami Aroma Cup', value: 'origami_aroma' },
  ],
  pour_style: [
    { label: 'Center Focused', value: 'center' },
    { label: 'Spiral', value: 'spiral'},
  ],
  water_type: [
    { label: 'Straight Distilled', value: 'distilled' },
    { label: 'TWW Light', value: 'tww_light' },
    { label: 'TWW Medium', value: 'tww_medium' },
    { label: 'TWW Dark', value: 'tww_dark' },
    { label: 'TWW Espresso', value: 'tww_espresso' },
    { label: 'TWW Cold Brew', value: 'tww_cold_brew' },
    { label: 'TWW Low Acid', value: 'tww_low_acid' },
    { label: 'Tap Water', value: 'tap' },
  ],
  filter_type: [
    { label: 'Origami', value: 'origami' },
  ],
  filter_brand: [
    { label: 'Origami', value: 'origami' },
  ],
  pre_wet: [
    { label: 'Yes', value: 'wet' },
    { label: 'No', value: 'dry' },
  ],
};

export const pouroverConfig = {
  key: 'pourover',
  label: 'Pourover Brew',
  labelPlural: 'Pourover Brews',
  base: `${BREW_BASE}/pourover`,
  uriPath: 'pourover/',

  columns: [
    { id: "date", label: "Date", minWidth: 100, orderingField: "brew_log__date" },
    { id: "bean", label: "Bean", minWidth: 160, orderingField: "brew_log__bean__name" },
    { id: "extraction_rating", label: "Rating", minWidth: 80 },
    { id: "dripper", label: "Dripper", minWidth: 100 },
    { id: "grinder", label: "Grinder", minWidth: 140 },
  ],

  fields: [
    {
      type: "dropdown",
      name: "bean",
      label: "Bean",
      required: true,
      size: { xs: 12, sm: 8, md: 8 },
      optionSource: "beans",
      editDisable: true,
    },
    {
      type: "date_time",
      name: "date",
      label: "Date & Time",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      defaultNow: true,
    },
    { type: "divider" },

    {
      type: "dropdown",
      name: "dripper",
      label: "Dripper",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      options: POUROVER_STATIC_OPTIONS.dripper,
      defaultValue: 'origami',
    },
    {
      type: "dropdown",
      name: "filter_brand",
      label: "Filter Brand",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      options: POUROVER_STATIC_OPTIONS.filter_brand,
      defaultValue: 'origami',
    },
    {
      type: "text_numeric",
      name: "filter_count",
      label: "Filter Count",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      placeholder: "1",
      defaultValue: 1,
    },
    {
      type: "dropdown",
      name: "filter_type",
      label: "Filter Type",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      options: POUROVER_STATIC_OPTIONS.filter_type,
      defaultValue: 'origami',
    },
    {
      type: "dropdown",
      name: "pre_wet",
      label: "Pre-wet filter?",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      options: POUROVER_STATIC_OPTIONS.pre_wet,
      defaultValue: 'wet',
    },
    {
      type: "spacer",
      size: { xs: 0, sm: 4, md: 4 },
      color: "rgba(180, 140, 100, 0)",
    },
    {
      type: "dropdown",
      name: "kettle",
      label: "Kettle",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      optionSource: "kettles",
      defaultValue: '1MRGE9cw',
    },
    {
      type: "dropdown",
      name: "scale",
      label: "Scale",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      optionSource: "scales",
      defaultValue: 'gBgrpqk1',
    },
    {
      type: "dropdown",
      name: "cup",
      label: "Cup",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      options: POUROVER_STATIC_OPTIONS.cup,
      defaultValue: 'ceramic',
    },
    { type: "divider" },

    {
      type: "dropdown",
      name: "grinder",
      label: "Grinder",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      optionSource: "grinders",
      defaultValue: 'cP37x_fF',
    },
    {
      type: "text_numeric",
      name: "grind_rotations",
      label: "Grind Rotations",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      placeholder: "2",
      defaultValue: 2,
    },
    {
      type: "text_numeric",
      name: "grind_position",
      label: "Grind Position",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      placeholder: "8.0",
      // defaultValue: 10,
    },
    {
      type: "dropdown",
      name: "water_type",
      label: "Water Type",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      options: POUROVER_STATIC_OPTIONS.water_type,
      defaultValue: 'tww_light',
    },
    {
      type: "spacer",
      size: { xs: 0, sm: 8, md: 8 },
      color: "rgba(180, 140, 100, 0)",
    },
    {
      type: "text_numeric",
      name: "temp",
      label: "Water Temp (C°)",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      placeholder: "94",
    },
    {
      type: "text_numeric",
      name: "water",
      label: "Water (g)",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      placeholder: "320",
    },
    {
      type: "text_numeric",
      name: "weight",
      label: "Bean Weight (g)",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      placeholder: "20",
    },
    { type: "divider" },

    {
      type: "event_list",
      component: "pourover",
      name: "pour_events",
      label: "Pour Events",
      required: false,
    },

      {
      type: "spacer",
      size: { xs: 0, sm: 4, md: 4 },
      color: "rgba(180, 140, 100, 0)",
    },
    {
      type: "text_numeric",
      name: "stop_time",
      label: "Stop Time (Taken Off Cup)",
      required: true,
      size: { xs: 12, sm: 4, md: 4 },
      placeholder: "2:18",
      inputStyle: "duration",
    },
    {
      type: "spacer",
      size: { xs: 0, sm: 4, md: 4 },
      color: "rgba(180, 140, 100, 0)",
    },


    { type: "divider" },

    {
      type: "long_text",
      name: "notes",
      label: "Notes",
      required: false,
      size: { xs: 12 },
      placeholder: "Tasting notes, what you'd change next time",
    },

    {
      type: "rating",
      name: "extraction_rating",
      label: "Extraction Rating",
      required: true,
      size: { xs: 12, sm: 6, md: 6 },
    },
  ],
};