services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - VITE_HOST=0.0.0.0
    depends_on:
      - backend