# Generated by Django 5.2.8 on 2026-03-30 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlavorNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roast_level', models.CharField(blank=True, choices=[('light', 'Light'), ('light_medium', 'Light-Medium'), ('medium', 'Medium'), ('medium_dark', 'Medium-Dark'), ('dark', 'Dark')], max_length=50)),
                ('organic_or_not', models.CharField(blank=True, choices=[('organic', 'Organic'), ('not_organic', 'Not Organic')], max_length=20)),
                ('washing_style', models.CharField(blank=True, choices=[('washed', 'Washed'), ('natural', 'Natural'), ('fermented', 'Fermented'), ('honey', 'Honey')], max_length=50)),
                ('caff_or_decaf', models.CharField(choices=[('caffeinated', 'Caffeinated'), ('decaffeinated', 'Decaffeinated')], max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('roast_date', models.DateField(blank=True, null=True)),
                ('min_elevation', models.IntegerField(blank=True, null=True)),
                ('max_elevation', models.IntegerField(blank=True, null=True)),
                ('short_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('origin_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.countries')),
                ('flavor_notes', models.ManyToManyField(blank=True, null=True, related_name='beans', to='coffee.flavornotes')),
            ],
        ),
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('business_type', models.CharField(blank=True, choices=[('roaster', 'Roaster'), ('cafe', 'Cafe'), ('roaster_cafe', 'Roaster/Cafe')], max_length=80)),
                ('website', models.URLField(blank=True, null=True)),
                ('social', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state_region', models.CharField(blank=True, max_length=200)),
                ('short_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.countries')),
            ],
        ),
        migrations.CreateModel(
            name='CafeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(max_length=200)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('bean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.bean')),
                ('roaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.roaster')),
            ],
        ),
        migrations.AddField(
            model_name='bean',
            name='roaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beans', to='coffee.roaster'),
        ),
    ]
