# Generated by Django 5.2.8 on 2025-11-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roaster', models.CharField(max_length=200)),
                ('origin_country', models.CharField(blank=True, help_text='Country of origin (e.g. Ethiopia, Guatemala)', max_length=100)),
            ],
        ),
    ]
