# Generated by Django 5.2.8 on 2025-12-05 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state_region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bean',
            name='caff_or_decaf',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bean',
            name='max_elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bean',
            name='min_elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bean',
            name='organic_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bean',
            name='roast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bean',
            name='roast_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bean',
            name='washing_style',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bean',
            name='roaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beans', to='coffee.roaster'),
        ),
    ]
