# Generated by Django 5.2.8 on 2026-04-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafelog',
            old_name='logged_at',
            new_name='drink_date',
        ),
    ]
