# Generated by Django 5.2.8 on 2026-04-06 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_rename_logged_at_cafelog_drink_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CafeLog',
            new_name='Drink',
        ),
    ]
