# Generated by Django 5.2.8 on 2025-12-05 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_roaster_bean_caff_or_decaf_bean_max_elevation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OriginCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bean',
            name='origin_country',
        ),
        migrations.AddField(
            model_name='roaster',
            name='business_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='roaster',
            name='notes',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='roaster',
            name='social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bean',
            name='caff_or_decaf',
            field=models.CharField(default='Caffeinated', max_length=20),
        ),
        migrations.AlterField(
            model_name='bean',
            name='roaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beans', to='coffee.origincountry'),
        ),
    ]
