# Generated by Django 5.2.8 on 2026-04-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_rename_cafelog_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_date',
            field=models.DateField(),
        ),
    ]
