# Generated by Django 5.2.8 on 2025-12-05 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_flavornotes_origincountry_remove_bean_origin_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.origincountry'),
        ),
        migrations.AlterField(
            model_name='bean',
            name='roaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beans', to='coffee.roaster'),
        ),
    ]
