# Generated by Django 5.2.8 on 2025-12-05 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_bean_origin_country_alter_bean_roaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roaster',
            name='location',
        ),
    ]
