# Generated by Django 5.2.8 on 2026-01-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_remove_roaster_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='flavor_notes',
            field=models.ManyToManyField(blank=True, related_name='beans', to='coffee.flavornotes'),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
