# Generated by Django 5.2.8 on 2026-04-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_drink_short_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='iso_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
