# Generated by Django 5.2.8 on 2026-04-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_countries_iso_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roaster',
            name='state_region',
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identifier_code', models.CharField(max_length=200)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.countries')),
            ],
        ),
        migrations.AddField(
            model_name='roaster',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.region'),
        ),
    ]
