# Generated by Django 5.2.8 on 2026-03-04 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_bean_flavor_notes_alter_roaster_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(max_length=200)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('roaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.roaster')),
            ],
        ),
    ]
