# Generated by Django 5.2.8 on 2026-03-22 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_cafelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafelog',
            name='bean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.bean'),
        ),
    ]
