# Generated by Django 5.2.8 on 2026-06-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_remove_roaster_state_region_region_roaster_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='washing_style',
            field=models.CharField(blank=True, choices=[('washed', 'Washed'), ('natural', 'Natural'), ('honey', 'Honey'), ('washed_natural', 'Washed & Natural'), ('anaerobic_natural', 'Anaerobic Natural'), ('anaerobic_washed', 'Anaerobic Washed')], max_length=50),
        ),
    ]
