# Generated by Django 5.2.8 on 2026-03-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_cafelog_bean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='caff_or_decaf',
            field=models.CharField(choices=[('caffeinated', 'Caffeinated'), ('decaffeinated', 'Decaffeinated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bean',
            name='organic_or_not',
            field=models.CharField(choices=[('organic', 'Organic'), ('notOrganic', 'Not Organic')], default=False),
        ),
        migrations.AlterField(
            model_name='bean',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('lightMedium', 'Light-Medium'), ('medium', 'Medium'), ('mediumDark', 'Medium-Dark'), ('dark', 'Dark')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bean',
            name='washing_style',
            field=models.CharField(blank=True, choices=[('washed', 'Washed'), ('natural', 'Natural'), ('fermented', 'Fermented'), ('honey', 'Honey')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='business_type',
            field=models.CharField(blank=True, choices=[('roaster', 'Roaster'), ('cafe', 'Cafe')], max_length=80),
        ),
    ]
