# Generated by Django 5.2.8 on 2026-06-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_alter_bean_roast_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
