# Generated by Django 5.2.8 on 2026-03-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_alter_bean_caff_or_decaf_alter_bean_organic_or_not_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='organic_or_not',
            field=models.CharField(choices=[('organic', 'Organic'), ('not_organic', 'Not Organic')], default=False),
        ),
        migrations.AlterField(
            model_name='bean',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('light_medium', 'Light-Medium'), ('medium', 'Medium'), ('medium_dark', 'Medium-Dark'), ('dark', 'Dark')], max_length=50),
        ),
    ]
