# Generated by Django 5.2.8 on 2026-03-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_alter_bean_organic_or_not_alter_bean_roast_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='organic_or_not',
            field=models.CharField(choices=[('organic', 'Organic'), ('not_organic', 'Not Organic')], max_length=20),
        ),
    ]
