# Generated by Django 5.2.8 on 2026-06-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_bean_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('country', models.ManyToManyField(to='coffee.countries')),
            ],
        ),
    ]
