# Generated by Django 5.2.8 on 2026-06-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0011_mapzone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapzone',
            old_name='country',
            new_name='countries',
        ),
    ]
