# Generated by Django 5.2.8 on 2026-03-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0011_alter_bean_organic_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
