# Generated by Django 5.2.8 on 2026-07-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0012_rename_country_mapzone_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='date_logged',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='date_logged',
            field=models.DateField(null=True),
        ),
    ]
