# Generated by Django 5.2.8 on 2026-03-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0012_bean_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='flavor_notes',
            field=models.ManyToManyField(blank=True, null=True, related_name='beans', to='coffee.flavornotes'),
        ),
    ]
