# Generated by Django 5.2.8 on 2026-03-29 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_alter_bean_flavor_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bean',
            name='organic_or_not',
            field=models.CharField(blank=True, choices=[('organic', 'Organic'), ('not_organic', 'Not Organic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='business_type',
            field=models.CharField(blank=True, choices=[('roaster', 'Roaster'), ('cafe', 'Cafe'), ('roaster_cafe', 'Roaster/Cafe')], max_length=80),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='state_region',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bean',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.countries'),
        ),
        migrations.DeleteModel(
            name='OriginCountry',
        ),
    ]
