# Generated by Django 5.2.8 on 2026-07-25 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_bean_date_logged_drink_date_logged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bean',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='roaster',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveField(
            model_name='bean',
            name='date_logged',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='date_logged',
        ),
        migrations.AddField(
            model_name='bean',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roaster',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
