# Generated by Django 5.2.8 on 2026-07-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_alter_bean_options_alter_drink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='purchased',
            field=models.BooleanField(default=True),
        ),
    ]
