# Generated by Django 5.2.8 on 2026-03-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_countries_alter_bean_organic_or_not_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roaster',
            name='country',
        ),
    ]
