# Generated by Django 5.2.8 on 2026-08-03 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0015_bean_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drinks_hosted', to='coffee.roaster'),
        ),
    ]
