# Generated by Django 5.2.8 on 2026-03-29 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0015_remove_roaster_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaster',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.countries'),
        ),
    ]
