# Generated by Django 5.2.8 on 2026-08-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0016_drink_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='opened_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
