# Generated by Django 5.2.8 on 2026-03-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0016_roaster_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roaster',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.countries'),
        ),
    ]
