# Generated by Django 5.2.8 on 2026-08-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0017_bean_opened_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
