# Generated by Django 5.2.8 on 2026-03-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0017_alter_roaster_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafelog',
            name='roaster',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='coffee.roaster'),
            preserve_default=False,
        ),
    ]
