# Generated by Django 5.2.8 on 2026-08-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0018_bean_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='bag_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
