# Generated by Django 5.2.8 on 2026-03-29 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0018_alter_cafelog_roaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafelog',
            name='roaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.roaster'),
        ),
    ]
