# Generated by Django 5.2.8 on 2026-08-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0019_bean_bag_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='used_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
