# Generated by Django 5.2.8 on 2026-08-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0020_bean_used_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='bag_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bean',
            name='used_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
