# Generated by Django 5.2.8 on 2026-08-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0021_alter_bean_bag_weight_alter_bean_used_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='opened_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
