# Generated by Django 5.2.8 on 2026-09-30 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0022_alter_bean_opened_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bean',
            name='washing_style',
            field=models.CharField(blank=True, choices=[('washed', 'Washed'), ('natural', 'Natural'), ('honey', 'Honey'), ('washed_natural', 'Washed & Natural'), ('anaerobic_natural', 'Anaerobic Natural'), ('anaerobic_washed', 'Anaerobic Washed'), ('fermented', 'Fermented'), ('unique', 'Unique')], max_length=50),
        ),
        migrations.AddField(
            model_name='bean',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.process'),
        ),
    ]
