# Generated by Django 5.2.8 on 2026-09-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0023_process_alter_bean_washing_style_bean_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'processes'},
        ),
        migrations.RemoveField(
            model_name='bean',
            name='washing_style',
        ),
    ]
