# Generated by Django 5.2.8 on 2026-09-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0024_alter_process_options_remove_bean_washing_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('light_medium', 'Light-Medium'), ('medium', 'Medium'), ('medium_dark', 'Medium-Dark'), ('dark', 'Dark'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
    ]
