# Generated by Django 5.2.8 on 2026-06-24 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrewMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_dormant', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BrewTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BrewVessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BrewMethodDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_table', models.CharField(max_length=200)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewmethod')),
            ],
        ),
        migrations.CreateModel(
            name='BrewRecipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_grams', models.IntegerField()),
                ('water_grams', models.IntegerField()),
                ('markup', models.TextField(max_length=200)),
                ('name', models.TextField(max_length=200)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewmethod')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewvessel')),
                ('cup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.cup')),
                ('grinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.grinder')),
                ('water', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.water')),
            ],
        ),
        migrations.CreateModel(
            name='BrewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('recipie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewrecipie')),
            ],
        ),
        migrations.CreateModel(
            name='BrewStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('step_type', models.TextField(max_length=200)),
                ('amount', models.TextField(max_length=200)),
                ('notes', models.TextField(max_length=1000)),
                ('recipie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewrecipie')),
            ],
        ),
        migrations.CreateModel(
            name='BrewRecipieBrewTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=200)),
                ('recipie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewrecipie')),
                ('brew_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewtool')),
            ],
        ),
        migrations.CreateModel(
            name='GrinderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('setting_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('grinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.grinder')),
            ],
        ),
        migrations.CreateModel(
            name='BrewRecipieGrinderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=200)),
                ('recipie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewrecipie')),
                ('grinder_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.grindersetting')),
            ],
        ),
        migrations.CreateModel(
            name='SessionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_source', models.TextField(max_length=200)),
                ('display_token', models.TextField(max_length=200)),
                ('expected_value', models.TextField(max_length=200)),
                ('actual_value', models.TextField(max_length=200)),
                ('reason', models.TextField(max_length=1000)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewsession')),
            ],
        ),
        migrations.CreateModel(
            name='VesselSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('setting_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewvessel')),
            ],
        ),
        migrations.CreateModel(
            name='BrewRecipieVesselSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=200)),
                ('recipie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewrecipie')),
                ('vessel_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.vesselsetting')),
            ],
        ),
    ]
