# Generated by Django 5.2.8 on 2026-08-15 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffee', '0017_bean_opened_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('short_id', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kettle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('short_id', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_id', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('espresso', 'Espresso'), ('milk_drink', 'Latte / Cappuccino'), ('aeropress', 'Aeropress'), ('pourover', 'Pourover'), ('cold_brew', 'Cold Brew')], max_length=20)),
                ('date', models.DateField()),
                ('extraction_rating', models.PositiveSmallIntegerField()),
                ('pull_number', models.PositiveSmallIntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('short_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brew_logs', to='coffee.bean')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AeropressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grind_rotations', models.PositiveSmallIntegerField()),
                ('grind_position', models.DecimalField(decimal_places=1, max_digits=3)),
                ('water_type', models.CharField(choices=[('distilled', 'Straight Distilled'), ('tww_light', 'TWW Light'), ('tww_medium', 'TWW Medium'), ('tww_dark', 'TWW Dark'), ('tww_espresso', 'TWW Espresso'), ('tww_cold_brew', 'TWW Cold Brew'), ('tww_low_acid', 'TWW Low Acid'), ('tap', 'Tap Water')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('base', models.CharField(choices=[('standard', 'Standard'), ('prismo', 'Fellow Prismo')], max_length=20)),
                ('filter', models.CharField(choices=[('none', 'None'), ('single', 'Single'), ('classic', 'Classic')], max_length=20)),
                ('orientation', models.CharField(choices=[('standard', 'Standard'), ('inverted', 'Inverted')], max_length=20)),
                ('pour_direction', models.CharField(choices=[('spin', 'Spin'), ('center', 'Center')], max_length=20)),
                ('cup', models.CharField(choices=[('ceramic', 'Ceramic'), ('glass', 'Glass'), ('origami_aroma', 'Origami Aroma Cup')], max_length=20)),
                ('temp', models.DecimalField(decimal_places=1, max_digits=5)),
                ('water', models.DecimalField(decimal_places=1, max_digits=6)),
                ('brew_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aeropress_detail', to='brew.brewlog')),
                ('grinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.grinder')),
                ('kettle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.kettle')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.scale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoffmannEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_time', models.DurationField()),
                ('rotation_count', models.PositiveSmallIntegerField()),
                ('aeropress_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoffmann_events', to='brew.aeropressdetail')),
            ],
            options={
                'ordering': ['rotation_time'],
            },
        ),
        migrations.CreateModel(
            name='PouroverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grind_rotations', models.PositiveSmallIntegerField()),
                ('grind_position', models.DecimalField(decimal_places=1, max_digits=3)),
                ('water_type', models.CharField(choices=[('distilled', 'Straight Distilled'), ('tww_light', 'TWW Light'), ('tww_medium', 'TWW Medium'), ('tww_dark', 'TWW Dark'), ('tww_espresso', 'TWW Espresso'), ('tww_cold_brew', 'TWW Cold Brew'), ('tww_low_acid', 'TWW Low Acid'), ('tap', 'Tap Water')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('filter_brand', models.CharField(max_length=200)),
                ('filter_count', models.PositiveSmallIntegerField()),
                ('dripper', models.CharField(choices=[('origami', 'Origami'), ('v60', 'V60')], default='origami', max_length=20)),
                ('cup', models.CharField(choices=[('ceramic', 'Ceramic'), ('glass', 'Glass'), ('origami_aroma', 'Origami Aroma Cup')], max_length=20)),
                ('water', models.DecimalField(decimal_places=1, max_digits=6)),
                ('temp', models.DecimalField(decimal_places=1, max_digits=5)),
                ('brew_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pourover_detail', to='brew.brewlog')),
                ('grinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.grinder')),
                ('kettle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.kettle')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.scale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PouroverPourEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pour_time', models.DurationField()),
                ('pour_amount', models.DecimalField(decimal_places=1, max_digits=6)),
                ('pourover_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pour_events', to='brew.pouroverdetail')),
            ],
            options={
                'ordering': ['pour_time'],
            },
        ),
        migrations.CreateModel(
            name='ColdBrewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grind_rotations', models.PositiveSmallIntegerField()),
                ('grind_position', models.DecimalField(decimal_places=1, max_digits=3)),
                ('water_type', models.CharField(choices=[('distilled', 'Straight Distilled'), ('tww_light', 'TWW Light'), ('tww_medium', 'TWW Medium'), ('tww_dark', 'TWW Dark'), ('tww_espresso', 'TWW Espresso'), ('tww_cold_brew', 'TWW Cold Brew'), ('tww_low_acid', 'TWW Low Acid'), ('tap', 'Tap Water')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('filter_style', models.CharField(choices=[('paper', 'Paper Filter'), ('mesh_bag', 'Mesh / Nut-Milk Bag'), ('strainer', 'Fine Mesh Strainer (post-steep)')], max_length=20)),
                ('water', models.DecimalField(decimal_places=1, max_digits=6)),
                ('settle_time', models.DurationField()),
                ('brew_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coldbrew_detail', to='brew.brewlog')),
                ('grinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.grinder')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.scale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
