# Generated by Django 5.2.8 on 2026-07-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrewMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_dormant', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BrewTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BrewVessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_grams', models.IntegerField()),
                ('water_grams', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BrewMethodDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_table', models.CharField(max_length=200)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewmethod')),
            ],
        ),
        migrations.CreateModel(
            name='GrinderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('grinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.grinder')),
            ],
        ),
        migrations.CreateModel(
            name='BrewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('recipie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.recipie')),
            ],
        ),
        migrations.CreateModel(
            name='RecipieBrewTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=200)),
                ('brew_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewtool')),
                ('recipie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.recipie')),
            ],
        ),
        migrations.CreateModel(
            name='RecipieGrinderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=200)),
                ('grinder_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.grindersetting')),
                ('recipie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.recipie')),
            ],
        ),
        migrations.CreateModel(
            name='RecipieTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=350)),
                ('cup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.cup')),
                ('grinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.grinder')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewmethod')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewvessel')),
                ('water', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.water')),
            ],
        ),
        migrations.AddField(
            model_name='recipie',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.recipietemplate'),
        ),
        migrations.CreateModel(
            name='BrewStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('step_type', models.TextField(max_length=200)),
                ('amount', models.TextField(max_length=200)),
                ('notes', models.TextField(max_length=1000)),
                ('recipie_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.recipietemplate')),
            ],
        ),
        migrations.CreateModel(
            name='VesselSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('setting_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewvessel')),
            ],
        ),
        migrations.CreateModel(
            name='RecipieVesselSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=200)),
                ('recipie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.recipie')),
                ('vessel_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.vesselsetting')),
            ],
        ),
    ]
