# Generated by Django 5.2.8 on 2026-08-15 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
        ('coffee', '0018_bean_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('opened', 'Opened'), ('finished', 'Finished')], max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='coffee.bean')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
