# Generated by Django 5.2.8 on 2026-07-19 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipietemplate',
            name='cup',
        ),
        migrations.RemoveField(
            model_name='recipietemplate',
            name='method',
        ),
        migrations.RemoveField(
            model_name='recipietemplate',
            name='water',
        ),
        migrations.AddField(
            model_name='recipie',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.brewmethod'),
        ),
        migrations.AddField(
            model_name='recipie',
            name='water',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.water'),
        ),
    ]
