# Generated by Django 5.2.8 on 2026-07-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grindersetting',
            name='name',
        ),
    ]
