# Generated by Django 5.2.8 on 2026-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0002_remove_grindersetting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewrecipie',
            name='name',
            field=models.CharField(max_length=350),
        ),
    ]
