# Generated by Django 5.2.8 on 2026-08-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0002_baglifecycleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropressdetail',
            name='pre_wet',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouroverdetail',
            name='filter_type',
            field=models.CharField(choices=[('classic', 'Classic')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouroverdetail',
            name='pre_wet',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouroverpourevent',
            name='pour_style',
            field=models.CharField(choices=[('center', 'Center Focused'), ('clockwise', 'Clockwise')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
