# Generated by Django 5.2.8 on 2026-07-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0002_remove_recipietemplate_cup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='water_temp',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
    ]
