# Generated by Django 5.2.8 on 2026-07-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0003_recipie_water_temp'),
        ('coffee', '0012_rename_country_mapzone_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewsession',
            name='bean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.bean'),
        ),
    ]
