# Generated by Django 5.2.8 on 2026-08-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0003_aeropressdetail_pre_wet_pouroverdetail_filter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewlog',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
