# Generated by Django 5.2.8 on 2026-08-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_brewsession_bean'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewmethod',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='brewsession',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='brewtool',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='brewvessel',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='cup',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='grinder',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='grindersetting',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='recipie',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='recipietemplate',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='vesselsetting',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='water',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
