# Generated by Django 5.2.8 on 2026-08-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_alter_brewlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baglifecycleevent',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
