# Generated by Django 5.2.8 on 2026-08-21 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0005_alter_baglifecycleevent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspressoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grind_rotations', models.PositiveSmallIntegerField()),
                ('grind_position', models.DecimalField(decimal_places=1, max_digits=3)),
                ('water_type', models.CharField(choices=[('distilled', 'Straight Distilled'), ('tww_light', 'TWW Light'), ('tww_medium', 'TWW Medium'), ('tww_dark', 'TWW Dark'), ('tww_espresso', 'TWW Espresso'), ('tww_cold_brew', 'TWW Cold Brew'), ('tww_low_acid', 'TWW Low Acid'), ('tap', 'Tap Water')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('wdt_used', models.BooleanField()),
                ('wdt_rotations', models.PositiveSmallIntegerField()),
                ('pull_time', models.DurationField()),
                ('water', models.DecimalField(decimal_places=1, max_digits=6)),
                ('machine', models.CharField(choices=[('gaggia_unmod', 'Gaggia Classic Pro E24 (Unmodded)')], default='gaggia_unmod', max_length=70)),
                ('puck_screen', models.CharField(choices=[('none', 'None'), ('normcore_316_ss', 'Normcore Puck Screen - 316 Stainless Steel')], default='none', max_length=50)),
                ('cup', models.CharField(choices=[('nc_high_ext', 'Normcore High Extraction Basket'), ('nc_prec', 'Normcore Precision Basket')], max_length=20)),
                ('basket', models.CharField(choices=[('none', 'None'), ('normcore_316_ss', 'Normcore Puck Screen - 316 Stainless Steel')], max_length=50)),
                ('brew_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='espresso_detail', to='brew.brewlog')),
                ('grinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.grinder')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.scale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
