# Generated by Django 5.2.8 on 2026-08-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0006_espressodetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropressdetail',
            name='pre_wet',
            field=models.CharField(choices=[('wet', 'Wet'), ('dry', 'Dry')], max_length=3),
        ),
        migrations.AlterField(
            model_name='espressodetail',
            name='wdt_used',
            field=models.CharField(choices=[('used', 'Used'), ('not_used', 'Not Used')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pouroverdetail',
            name='pre_wet',
            field=models.CharField(choices=[('wet', 'Wet'), ('dry', 'Dry')], max_length=3),
        ),
    ]
