# Generated by Django 5.2.8 on 2026-08-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0007_alter_aeropressdetail_pre_wet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espressodetail',
            name='tamper',
            field=models.CharField(choices=[('nc_41_flat', 'Normcore V4.1 Spring Loaded Tamper (Flat Base)')], default='nc_41_flat', max_length=50),
        ),
        migrations.AlterField(
            model_name='espressodetail',
            name='basket',
            field=models.CharField(choices=[('nc_high_ext', 'Normcore High Extraction Basket'), ('nc_prec', 'Normcore Precision Basket')], default='nc_prec', max_length=50),
        ),
    ]
