# Generated by Django 5.2.8 on 2026-08-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0008_espressodetail_tamper_alter_espressodetail_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espressodetail',
            name='water',
        ),
    ]
