# Generated by Django 5.2.8 on 2026-08-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0009_remove_espressodetail_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espressodetail',
            name='cup',
            field=models.CharField(choices=[('ceramic', 'Ceramic'), ('glass', 'Glass'), ('origami_aroma', 'Origami Aroma Cup')], max_length=20),
        ),
        migrations.AlterField(
            model_name='espressodetail',
            name='wdt_rotations',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
