# Generated by Django 5.2.8 on 2026-08-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0010_alter_espressodetail_cup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espressodetail',
            name='paper_filter_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='espressodetail',
            name='paper_filter_type',
            field=models.CharField(choices=[('none', 'None'), ('normcore', 'Normcore Filter')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='espressodetail',
            name='paper_filter_used',
            field=models.CharField(choices=[('used', 'Used'), ('not_used', 'Not Used')], default='not_used', max_length=10),
        ),
    ]
