# Generated by Django 5.2.8 on 2026-08-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0011_espressodetail_paper_filter_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropressdetail',
            name='pour_direction',
            field=models.CharField(choices=[('spiral', 'Spiral'), ('center', 'Center')], max_length=20),
        ),
    ]
