# Generated by Django 5.2.8 on 2026-08-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0012_alter_aeropressdetail_pour_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouroverdetail',
            name='filter_type',
            field=models.CharField(choices=[('origami', 'Origami')], max_length=20),
        ),
    ]
