# Generated by Django 5.2.8 on 2026-08-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0013_alter_pouroverdetail_filter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropressdetail',
            name='pour_direction',
            field=models.CharField(choices=[('spin', 'Spin'), ('center', 'Center')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pouroverdetail',
            name='filter_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('origami', 'Origami')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pouroverpourevent',
            name='pour_style',
            field=models.CharField(choices=[('center', 'Center Focused'), ('spiral', 'Spiral')], max_length=20),
        ),
    ]
