# Generated by Django 5.2.8 on 2026-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0014_alter_aeropressdetail_pour_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropressdetail',
            name='grind_position',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='aeropressdetail',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='coldbrewdetail',
            name='grind_position',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coldbrewdetail',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='espressodetail',
            name='grind_position',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='espressodetail',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pouroverdetail',
            name='grind_position',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pouroverdetail',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
