# Generated by Django 5.2.8 on 2026-09-07 18:00

from datetime import timedelta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0015_alter_aeropressdetail_grind_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espressodetail',
            name='pull_weight',
            field=models.DecimalField(decimal_places=3, default=36, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouroverpourevent',
            name='pour_duration',
            field=models.DurationField(default=timedelta(seconds=11)),
            preserve_default=False,
        ),
    ]