# Generated by Django 5.2.8 on 2026-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0016_espressodetail_pull_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropressdetail',
            name='filter',
            field=models.CharField(choices=[('none', 'None'), ('single', 'Single'), ('aeropress', 'Aeropress')], max_length=20),
        ),
    ]
