# Generated by Django 5.2.8 on 2026-09-12 23:19

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0017_alter_aeropressdetail_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropressdetail',
            name='press_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aeropressdetail',
            name='press_time',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
    ]
