# Generated by Django 5.2.8 on 2026-09-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0018_aeropressdetail_press_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouroverdetail',
            name='stop_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
