# Generated by Django 5.2.8 on 2026-09-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0019_pouroverdetail_stop_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('great', 'Great'), ('pro', 'Pro'), ('other', 'Other'), ('con', 'Con'), ('catastrophe', 'Catastrophe')], max_length=16)),
                ('methods', models.JSONField(blank=True, default=list)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='brewlog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='brew_logs', to='brew.brewtag'),
        ),
    ]
