# Generated by Django 5.2.8 on 2026-09-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0021_seed_brew_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewtag',
            name='category',
            field=models.CharField(choices=[('great', 'Great'), ('pro', 'Pro'), ('other', 'Other'), ('con', 'Con'), ('catastrophe', 'Catastrophe'), ('amazing', 'Amazing')], max_length=16),
        ),
    ]
