# Generated by Django 5.2.8 on 2026-10-03 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0022_alter_brewtag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewlog',
            name='style',
            field=models.CharField(choices=[('espresso', 'Espresso'), ('milk_drink', 'Latte / Cappuccino'), ('aeropress', 'Aeropress'), ('pourover', 'Pourover'), ('cold_brew', 'Cold Brew'), ('cupping', 'Cupping')], max_length=20),
        ),
        migrations.CreateModel(
            name='CuppingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grind_rotations', models.PositiveSmallIntegerField()),
                ('grind_position', models.DecimalField(decimal_places=2, max_digits=4)),
                ('water_type', models.CharField(choices=[('distilled', 'Straight Distilled'), ('tww_light', 'TWW Light'), ('tww_medium', 'TWW Medium'), ('tww_dark', 'TWW Dark'), ('tww_espresso', 'TWW Espresso'), ('tww_cold_brew', 'TWW Cold Brew'), ('tww_low_acid', 'TWW Low Acid'), ('tap', 'Tap Water')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('water', models.DecimalField(decimal_places=1, max_digits=6)),
                ('steep_time', models.DurationField()),
                ('brew_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cupping_detail', to='brew.brewlog')),
                ('grinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.grinder')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brew.scale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
