# Generated by Django 5.2.8 on 2026-10-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0023_alter_brewlog_style_cuppingdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldbrewdetail',
            name='settle_time',
        ),
        migrations.AddField(
            model_name='coldbrewdetail',
            name='steep_hours',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
